### ISSUE TITLE
Question: using this demo with a different config

### ISSUE THREAD

**Issue by Daimona** [phan/demo#11]
I'd love to fork this demo to provide an online demo for the taint-check plugin. All I'd need is basically be able to use a different config for running phan. AFAICS it should be doable if I just change the content of #phan_runner_source and adjust it to my needs, although that seems fragile. Is there a recommended way for my use case, or should I just go ahead with the above?

**Comment by TysonAndre** [comment]
Forking it and changing phan_runner_source would probably be the most straightforward and I don't have any changes planned that would be likely to make that stop working.

I'd considered having a popup menu where you could check/uncheck plugins and have those reflected in the generated query string, similar to how https://play.rust-lang.org/ has various tools you can select

**Comment by TysonAndre** [comment]
Unrelated: Is there an issue tracker for the taint-check plugin - I'm not sure which issues for bugs/new features have already been filed

**Comment by Daimona** [comment]
> Forking it and changing phan_runner_source would probably be the most straightforward and I don't have any changes planned that would be likely to make that stop working.

Gotcha, thank you! I'm closing this as resolved.

> Unrelated: Is there an issue tracker for the taint-check plugin - I'm not sure which issues for bugs/new features have already been filed

Yeah, issues are tracked on https://phabricator.wikimedia.org/.
 - Task creation form: https://phabricator.wikimedia.org/maniphest/task/edit/form/1/
 - You can use the same account created for gerrit, just select "developer login" when prompted to login
 - As `Tags`, just add `phan-taint-check-plugin` 
 - To see open issues, two views are available: [workboard](https://phabricator.wikimedia.org/project/view/3149/) and [simple list](https://phabricator.wikimedia.org/maniphest/?project=PHID-PROJ-r6llepzuanwxwlonso26&statuses=open()&group=none&order=newest#R)
 - I often forget to create an issue when I write new features / fix bugs, so the issue list is incomplete. I am automatically subscribed to new issues, so, if you open one, I can link it to a commit on gerrit if it exists
 - I thought it was still possible to open new issues on github, but apparently I'm wrong.
